name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: read

jobs:
  app:
    name: Home Assistant app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: frenck/action-addon-linter@v2.21
        with:
          path: ./unifi_protect_ingress

  python:
    name: Python tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - run: pip install aiohttp==3.12.15
      - run: python -m unittest discover -s tests -v

